---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  grafana
  namespace: monitor
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app:  grafana
    spec:
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: storage
          hostPath:
              path: /data/grafana
      nodeSelector:
        type: monitor
      securityContext:
        runAsUser: 0  
      containers:
      - name: grafana
        image: grafana/grafana:6.5.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: grafana
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin@321^
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: storage
          mountPath: /var/lib/grafana

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitor
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - name: grafana
    nodePort: 30001
    port: 3000
    targetPort: grafana 
    protocol: TCP
