apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: monitor
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9121

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: monitor
  annotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379 
  - name: redis-exporter
    port: 9121
    targetPort: 9121
